# common settings

baseURL = 'http://journal.clairtor.com/'
languageCode = 'en-AU'
title = "Clairtör's Journal"
theme = 'journal'
[params]
  author = 'Claire Weymouth'
  description = "Claire Weymouth's personal journal"
  slogan = "Unwelcome to my Asocial Network."