#!/usr/bin/env python

from pathlib import Path
import subprocess
import argparse
import os


class ascii_colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def build(args):
    if args.sites == []:
        sites = os.listdir("./src/sites/")
    else:
        sites = args.sites
    for site in sites:
        try:
            config_path = Path(f"./src/sites/{site}/config")
            print(config_path)
            if not config_path.exists():
                raise Exception("Site does not exist.")
            else:
                command = subprocess.run(["hugo", "--environment claire-websites", f"--configDir sites/{site}/config"],
                                        stdout=subprocess.PIPE,
                                        stderr=subprocess.PIPE,
                                        text=True,
                                        cwd="./src")
        except Exception as err:
            print(ascii_colors.FAIL + "Error building site " +
                  ascii_colors.HEADER + site + ascii_colors.ENDC + "\n")
            print("\t" + err.__str__() + "\n")
        else:
            print(ascii_colors.OKGREEN + "Building site " +
                  ascii_colors.HEADER + site + ascii_colors.ENDC + "\n")
            for line in command.stdout.splitlines():
                print(f"\t{line}")
            print('')


def deploy():
    print(ascii_colors.OKGREEN +
          "Deploying all currently built sites " + ascii_colors.ENDC + "\n")
    command = subprocess.run(["rsync", "-vr", "./public/", "claire@71.19.144.253:/home/claire/containers/caddy/sites/"],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             text=True)
    for line in command.stdout.splitlines():
        print(f"\t{line}")
    print('')

def main():
    print(ascii_colors.BOLD + "web-precence" + ascii_colors.ENDC + "\n")

    # Create the parser object
    parser = argparse.ArgumentParser(
        description="Helper functions for the web-presence hugo repository",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Create the subparsers for our script
    subparsers = parser.add_subparsers(dest="command")

    # Create the build subparser
    build_subparser = subparsers.add_parser(
        "build", help="Build some or all of the sites")
    build_subparser.add_argument(
        "sites", nargs="*", type=str, help="site(s) to build")

    # Create the deploy subparser
    deploy_subparser = subparsers.add_parser(
        "deploy", help="Deploy some or all of the sites to a target")

    # Create the push subparser
    push_subparser = subparsers.add_parser(
        "push", help="Builds all sites and publishes them")
    push_subparser.add_argument(
        "sites", nargs="*", type=str, help="site(s) to build")

    # Parse the arguments
    args = parser.parse_args()

    # Perform actions accordingly based on chosen subcommand
    if args.command == "build":
        build(args)
    elif args.command == "deploy":
        deploy()
    elif args.command == "push":
        print(ascii_colors.HEADER +
            "Doing all the things! " + ascii_colors.ENDC + "\n")
        build()
        deploy()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()