[main]

    [claire-websites-core]
        git = "git@github.com:clairtor/com.clairecode.git"
        git_branch = "main"
        local_path = "src/sites/com.clairecode"

[themes]

    [themes.claire-websites-theme]
        git = "git@github.com:clairtor/claire-websites-theme.git"
        git_branch = "main"
        local_path = "src/themes/claire-websites-theme"

[sites]
    [com.clairecode]
        git = "git@github.com:clairtor/com.clairecode.git"
        git_branch = "main"
        local_path = "src/sites/com.clairecode"

    [com.clairtor]
        git = "git@github.com:clairtor/com.clairtor.git"
        git_branch = "main"
        local_path = "src/sites/com.clairtor"

    [com.clairtor.journal]
        git = "git@github.com:clairtor/com.clairtor.journal.git"
        git_branch = "main"
        local_path = "src/sites/com.clairtor.journal"






