# Common Settings
baseURL = 'http://clairecode.com/'
languageCode = 'en-AU'
title = 'Clairecode'
theme = "claire"
[params]
  author = "Claire Weymouth"
  description = "Claire Weymouth's technical and business website."
  slogan = "Thinking, Implementing and Iterating"